
test: test_choose test_update

test_gui: test_gui_lone

test_gui_lone:  # Lone parameter selection gui elements.
	python test/gui/lone.py

test_update:
	python test/update.py
test_choose:
	python test/choose.py

